"""Generate the f16-output variants of the elementwise kernels.

Activations that only ever feed a matmul do not need to be f32 in memory. The
matmul narrows them to f16 on the way into LDS anyway, so producing them as f16
halves the traffic on both sides of the handoff. The residual stream, the norm
statistics and the final output stay f32.
"""
from pathlib import Path

KERNELS = Path(__file__).resolve().parent.parent / "kernels"

EDITS = {
    "layernorm_f32.loom": (
        "layernorm_f32_to_f16.loom", "dinov3_layernorm_f32", "dinov3.layernorm_f32",
        [
            ("%output_view = buffer.view %output_noalias[%c0_offset] : buffer -> view<[%token_count]x[%hidden_size]xf32>",
             "%output_view = buffer.view %output_noalias[%c0_offset] : buffer -> view<[%token_count]x[%hidden_size]xf16>"),
            ("""      %result = scalar.addf<reassoc|nnan|ninf|nsz> %scaled, %shift : f32
      view.store %result, %output_view[%token, %channel] : f32, view<[%token_count]x[%hidden_size]xf32>""",
             """      %result = scalar.addf<reassoc|nnan|ninf|nsz> %scaled, %shift : f32
      %narrow = scalar.fptrunc %result : f32 to f16
      view.store %narrow, %output_view[%token, %channel] : f16, view<[%token_count]x[%hidden_size]xf16>"""),
        ],
        "// VARIANT: writes f16. The consumer is a matmul, which would narrow it anyway.",
    ),
    "swiglu_f32.loom": (
        "swiglu_f16.loom", "dinov3_swiglu_f32", "dinov3.swiglu_f32",
        [
            ("""  %gate_view = buffer.view %gate_global[%c0_offset] : buffer -> view<[%token_count]x[%row_stride]xf32>
  %up_view = buffer.view %up_global[%c0_offset] : buffer -> view<[%token_count]x[%row_stride]xf32>
  %out_view = buffer.view %out_global[%c0_offset] : buffer -> view<[%token_count]x[%width]xf32>""",
             """  %gate_view = buffer.view %gate_global[%c0_offset] : buffer -> view<[%token_count]x[%row_stride]xf16>
  %up_view = buffer.view %up_global[%c0_offset] : buffer -> view<[%token_count]x[%row_stride]xf16>
  %out_view = buffer.view %out_global[%c0_offset] : buffer -> view<[%token_count]x[%width]xf16>"""),
            ("""      %gate_value = view.load %gate_view[%token, %channel] : view<[%token_count]x[%row_stride]xf32> -> f32
      %up_value = view.load %up_view[%token, %channel] : view<[%token_count]x[%row_stride]xf32> -> f32
      %activated = scalar.siluf<afn> %gate_value : f32
      %result = scalar.mulf %activated, %up_value : f32
      view.store %result, %out_view[%token, %channel] : f32, view<[%token_count]x[%width]xf32>""",
             """      %gate_half = view.load %gate_view[%token, %channel] : view<[%token_count]x[%row_stride]xf16> -> f16
      %up_half = view.load %up_view[%token, %channel] : view<[%token_count]x[%row_stride]xf16> -> f16
      %gate_value = scalar.extf %gate_half : f16 to f32
      %up_value = scalar.extf %up_half : f16 to f32
      %activated = scalar.siluf<afn> %gate_value : f32
      %result = scalar.mulf %activated, %up_value : f32
      %narrow = scalar.fptrunc %result : f32 to f16
      view.store %narrow, %out_view[%token, %channel] : f16, view<[%token_count]x[%width]xf16>"""),
        ],
        "// VARIANT: f16 in and out. Both sides are matmul handoffs; the silu itself is f32.",
    ),
    "flash_attention_f16_wmma.loom": (
        "flash_attention_f16_wmma_cf16.loom", "dinov3_flash_attention_f16_wmma",
        "dinov3.flash_attention_f16_wmma",
        [
            ("%out_view = buffer.view %out_global[%c0_offset] : buffer -> view<[%token_count]x[%hidden_size]xf32>",
             "%out_view = buffer.view %out_global[%c0_offset] : buffer -> view<[%token_count]x[%hidden_size]xf16>"),
            ("""    %values = vector.load %result_view[%publish_row, %publish_dim] : view<16x212xf32> -> vector<4xf32>""",
             """    %wide = vector.load %result_view[%publish_row, %publish_dim] : view<16x212xf32> -> vector<4xf32>
    %values = vector.fptrunc %wide : vector<4xf32> to vector<4xf16>"""),
            ("""    vector.store %values, %out_view[%bounded, %out_slot] : vector<4xf32>, view<[%token_count]x[%hidden_size]xf32>""",
             """    vector.store %values, %out_view[%bounded, %out_slot] : vector<4xf16>, view<[%token_count]x[%hidden_size]xf16>"""),
        ],
        "// VARIANT: writes f16 straight into the output projection's activation.",
    ),
}


def main() -> None:
    for source, (target, symbol, namespace, edits, note) in EDITS.items():
        text = (KERNELS / source).read_text()
        suffix = "_" + target.split("_")[-1].removesuffix(".loom")
        for old, new in edits:
            assert old in text, f"{source}: anchor moved\n{old[:80]}"
            text = text.replace(old, new)
        text = text.replace(symbol, symbol + suffix).replace(namespace, namespace + suffix)
        text = (note + f"\n// GENERATED by tools/gen_f16_variants.py from {source}.\n" + text)
        (KERNELS / target).write_text(text)
        print(f"wrote {target}")


if __name__ == "__main__":
    main()
