"""Generate the WMMA matmul variants.

C[m, n] = sum_k A[m, k] * W[n, k] + bias[n], W always f16, accumulation always
f32. What varies is the activation dtype at the two ends:

  a_dtype=f32  A is read as f32 and narrowed while being staged into LDS
  a_dtype=f16  A is already f16, so the stage is a straight copy
  c_dtype=f32  the usual output
  c_dtype=f16  for outputs whose only consumer is another matmul or an
               elementwise kernel, halving the bandwidth on both sides

The f16 activation path matters more than it looks: the gate/up projection has
48 column tiles, so its A operand is re-read 48 times across the workgroups.
"""
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent / "kernels/matmul_bias_f16_wmma.loom"

A_F32 = '''      %a_values = scf.if %m_in_range -> (vector<4xf16>) {
        %bounded = index.assume %source_m [lt(%source_m, %m_size)] : index
        %wide = vector.load %a_view[%bounded, %source_k] : view<[%m_size]x[%k_size]xf32> -> vector<4xf32>
        %narrow = vector.fptrunc %wide : vector<4xf32> to vector<4xf16>
        scf.yield %narrow : vector<4xf16>
      } else {
        scf.yield %zero_f16x4 : vector<4xf16>
      }'''

A_F16 = '''      %a_values = scf.if %m_in_range -> (vector<4xf16>) {
        %bounded = index.assume %source_m [lt(%source_m, %m_size)] : index
        %narrow = vector.load %a_view[%bounded, %source_k] : view<[%m_size]x[%k_size]xf16> -> vector<4xf16>
        scf.yield %narrow : vector<4xf16>
      } else {
        scf.yield %zero_f16x4 : vector<4xf16>
      }'''

C_F32 = '''        vector.store %biased, %c_view[%bounded, %out_col] : vector<4xf32>, view<[%m_size]x[%n_size]xf32>'''

C_F16 = '''        %narrow = vector.fptrunc %biased : vector<4xf32> to vector<4xf16>
        vector.store %narrow, %c_view[%bounded, %out_col] : vector<4xf16>, view<[%m_size]x[%n_size]xf16>'''


def generate(a_dtype: str, c_dtype: str) -> tuple[str, str]:
    text = BASE.read_text()
    suffix = ""
    if a_dtype == "f16":
        suffix += "_af16"
    if c_dtype == "f16":
        suffix += "_cf16"
    if not suffix:
        return "", ""

    if a_dtype == "f16":
        assert A_F32 in text, "A staging block moved"
        text = text.replace(A_F32, A_F16)
        text = text.replace(
            "%a_view = buffer.view %a_global[%c0_offset] : buffer -> view<[%m_size]x[%k_size]xf32>",
            "%a_view = buffer.view %a_global[%c0_offset] : buffer -> view<[%m_size]x[%k_size]xf16>")
    if c_dtype == "f16":
        assert C_F32 in text, "C epilogue moved"
        text = text.replace(C_F32, C_F16)
        text = text.replace(
            "%c_view = buffer.view %c_global[%c0_offset] : buffer -> view<[%m_size]x[%n_size]xf32>",
            "%c_view = buffer.view %c_global[%c0_offset] : buffer -> view<[%m_size]x[%n_size]xf16>")

    text = text.replace("dinov3_matmul_bias_f16_wmma", f"dinov3_matmul_bias_f16_wmma{suffix}")
    text = text.replace("dinov3.matmul_bias_f16_wmma.", f"dinov3.matmul_bias_f16_wmma{suffix}.")
    text = text.replace("@dinov3_matmul_wmma_gfx11", f"@dinov3_matmul_wmma{suffix}_gfx11")
    note = {
        ("f16", "f32"): "// VARIANT: activations arrive f16 (no narrowing on the way into LDS).",
        ("f32", "f16"): "// VARIANT: output is f16, for a consumer that only feeds another kernel.",
        ("f16", "f16"): "// VARIANT: f16 in and f16 out.",
    }[(a_dtype, c_dtype)]
    text = text.replace("// GENERATED", "// GENERATED")
    text = (note + "\n// GENERATED by tools/gen_matmul_wmma.py from matmul_bias_f16_wmma.loom.\n"
            + text)
    return suffix, text


if __name__ == "__main__":
    kernels = BASE.parent
    for a, c in (("f16", "f32"), ("f32", "f16"), ("f16", "f16")):
        suffix, text = generate(a, c)
        path = kernels / f"matmul_bias_f16_wmma{suffix}.loom"
        path.write_text(text)
        print(f"wrote {path.name}  (A={a}, C={c})")
