"""Generate the f16-output variant of the online attention kernel.

The attention result only ever feeds the output projection, which narrows it to
f16 on the way into LDS anyway, so producing it as f16 halves the traffic on
both sides of the handoff.

This used to generate a family of f32/f16 variants for every elementwise kernel
and matmul. Those alternate paths are gone -- there is one inference path now --
and the kernels they fed live in experiments/superseded/.
"""
from pathlib import Path

KERNELS = Path(__file__).resolve().parent.parent / "kernels"

SOURCE = "attention_online_f16_wmma.loom"
TARGET = "attention_online_f16_wmma_cf16.loom"
SYMBOL = "dinov3_attention_online_f16_wmma"
NAMESPACE = "dinov3.attention_online_f16_wmma"
SUFFIX = "_cf16"

EDITS = [
    ("  %out_view = buffer.view %out_global[%c0_offset] : buffer -> view<[%token_count]x[%hidden_size0]xf32>",
     "  %out_view = buffer.view %out_global[%c0_offset] : buffer -> view<[%token_count]x[%hidden_size0]xf16>"),
    ("      %values = vector.load %result_view[%row, %column] : view<16x64xf32> -> vector<4xf32>",
     """      %wide = vector.load %result_view[%row, %column] : view<16x64xf32> -> vector<4xf32>
      %values = vector.fptrunc %wide : vector<4xf32> to vector<4xf16>"""),
    ("      vector.store %values, %out_view[%global_row, %out_column] : vector<4xf32>, view<[%token_count]x[%hidden_size0]xf32>",
     "      vector.store %values, %out_view[%global_row, %out_column] : vector<4xf16>, view<[%token_count]x[%hidden_size0]xf16>"),
]

NOTE = "// VARIANT: writes f16 straight into the output projection's activation."


def main() -> None:
    text = (KERNELS / SOURCE).read_text()
    for old, new in EDITS:
        assert old in text, f"{SOURCE}: anchor moved\n{old[:80]}"
        text = text.replace(old, new)
    text = text.replace(SYMBOL, SYMBOL + SUFFIX).replace(NAMESPACE, NAMESPACE + SUFFIX)
    text = NOTE + f"\n// GENERATED by tools/gen_f16_variants.py from {SOURCE}.\n" + text
    (KERNELS / TARGET).write_text(text)
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
