"""Generate the matmul kernels.

C[m, n] = sum_k A[m, k] * W[n, k] + bias[n], with W row-major [N, K] — exactly a
torch nn.Linear weight, so nothing in the model needs a transpose.

Two tile shapes are emitted. 64x64 has the better compute-to-LDS ratio and wins
whenever there is enough work to fill the 40 CUs; 32x32 gives four times as many
workgroups and wins on the narrow shapes (N=384 at 201 tokens is only 24
workgroups at 64x64, which leaves most of the GPU idle).

LDS rows are padded to KC+1 floats. Without the pad the four A reads a workitem
issues per k-step sit exactly 32 floats apart and hit the same LDS bank every
time; the odd stride spreads them. That pad alone was worth 10x.
"""
from pathlib import Path

KC = 32
THREADS = 256
GRID = 16          # workitems are a 16x16 grid over the tile
ROW = KC + 1       # padded LDS row stride


def generate(tile_m: int, tile_n: int, suffix: str) -> str:
    micro_m, micro_n = tile_m // GRID, tile_n // GRID
    slab_a, slab_w = tile_m * ROW, tile_n * ROW
    lds = slab_a + slab_w
    name = f"dinov3_matmul_bias_f32{suffix}"
    out: list[str] = []
    w = out.append

    w(f"""// C[m, n] = sum_k A[m, k] * W[n, k] + bias[n]   ({tile_m}x{tile_n} tile)
//
// W is row-major [N, K] — exactly a torch nn.Linear weight, so nothing in the
// model needs a transpose. One workgroup computes a {tile_m}x{tile_n} tile with 256
// workitems, each holding a {micro_m}x{micro_n} block of accumulators in registers across
// the whole K loop. LDS rows are padded to {ROW} floats to avoid bank conflicts.
//
// GENERATED by tools/gen_matmul.py — edit that, not this.
//
// N must be a multiple of {tile_n} and K of {KC}. M is a runtime value, bounds-checked.

amdgpu.target<gfx11-generic> @{name}_gfx11 {{subgroup_size = 32}}

config.decl @dinov3.matmul_bias_f32{suffix}.k_size : %value: index where [range(%value, {KC}, 8192), mul(%value, {KC})]

config.decl @dinov3.matmul_bias_f32{suffix}.n_size : %value: index where [range(%value, {tile_n}, 8192), mul(%value, {tile_n})]

kernel.def target(@{name}_gfx11) export("{name}") @{name}(%m_size: index) {{
  %c1 = index.constant 1 : index
  %tile_m = index.constant {tile_m} : index
  %tile_m_minus_one = index.constant {tile_m - 1} : index
  %tile_n = index.constant {tile_n} : index
  %threads = index.constant {THREADS} : index
  %n_size0 = config.get @dinov3.matmul_bias_f32{suffix}.n_size : index
  %m_rounded = index.add %m_size, %tile_m_minus_one : index
  %m_tiles = index.div %m_rounded, %tile_m : index
  %n_tiles = index.div %n_size0, %tile_n : index
  kernel.launch.config workgroups(%n_tiles, %m_tiles, %c1) workgroup_size(%threads, %c1, %c1) : index
}} launch(%m_size: index, %a: buffer, %w: buffer, %bias: buffer, %c: buffer) {{
  %k_size0 = config.get @dinov3.matmul_bias_f32{suffix}.k_size : index
  %n_size0 = config.get @dinov3.matmul_bias_f32{suffix}.n_size : index
  %k_size = index.assume %k_size0 [range(%k_size0, {KC}, 8192), mul(%k_size0, {KC})] : index
  %n_size = index.assume %n_size0 [range(%n_size0, {tile_n}, 8192), mul(%n_size0, {tile_n})] : index

  %c0 = index.constant 0 : index
  %c1 = index.constant 1 : index
  %c2 = index.constant 2 : index
  %c3 = index.constant 3 : index
  %grid = index.constant {GRID} : index
  %micro_m = index.constant {micro_m} : index
  %micro_n = index.constant {micro_n} : index
  %kc = index.constant {KC} : index
  %row = index.constant {ROW} : index
  %tile_m = index.constant {tile_m} : index
  %tile_n = index.constant {tile_n} : index
  %threads = index.constant {THREADS} : index
  %slab_a = index.constant {slab_a} : index
  %span_a = index.constant {tile_m * KC} : index
  %span_w = index.constant {tile_n * KC} : index
  %c0_offset = index.constant 0 : offset
  %lds_bytes = index.constant {lds * 4} : offset
  %zero = scalar.constant 0.0 : f32

  %tile_n_id = kernel.workgroup.id<x> : index
  %tile_m_id = kernel.workgroup.id<y> : index
  %workitem = kernel.workitem.id<x> : index

  %cell_n = index.rem %workitem, %grid : index
  %cell_m = index.div %workitem, %grid : index
  %local_n0 = index.mul %cell_n, %micro_n : index
  %local_m0 = index.mul %cell_m, %micro_m : index

  %base_m = index.mul %tile_m_id, %tile_m : index
  %base_n = index.mul %tile_n_id, %tile_n : index

  %a_global = buffer.assume.memory_space<global> %a : buffer
  %w_global = buffer.assume.memory_space<global> %w : buffer
  %bias_global = buffer.assume.memory_space<global> %bias : buffer
  %c_global = buffer.assume.memory_space<global> %c : buffer
  %a_view = buffer.view %a_global[%c0_offset] : buffer -> view<[%m_size]x[%k_size]xf32>
  %w_view = buffer.view %w_global[%c0_offset] : buffer -> view<[%n_size]x[%k_size]xf32>
  %bias_view = buffer.view %bias_global[%c0_offset] : buffer -> view<[%n_size]xf32>
  %c_view = buffer.view %c_global[%c0_offset] : buffer -> view<[%m_size]x[%n_size]xf32>

  %lds = buffer.alloca<workgroup> align(16) %lds_bytes : buffer
  %lds_view = buffer.view %lds[%c0_offset] : buffer -> view<{lds}xf32>
""")

    accs = [f"%acc{i}_{j}" for i in range(micro_m) for j in range(micro_n)]
    types = ", ".join(["f32"] * len(accs))
    sums = [a.replace("%acc", "%sum") for a in accs]
    nexts = [a.replace("%acc", "%next") for a in accs]
    init = ", ".join(f"{s} = %zero : f32" for s in sums)

    w(f"""  {', '.join(accs)} = scf.for %k_base = [%c0 to %k_size step %kc]({init}) -> ({types}) {{
    scf.for %slot = [%workitem to %span_a step %threads] {{
      %slab_row = index.div %slot, %kc : index
      %slab_k = index.rem %slot, %kc : index
      %lds_row = index.mul %slab_row, %row : index
      %lds_slot = index.add %lds_row, %slab_k : index
      %source_k = index.add %k_base, %slab_k : index
      %source_m = index.add %base_m, %slab_row : index
      %m_in_range = index.cmp ult, %source_m, %m_size : index
      %a_value = scf.if %m_in_range -> (f32) {{
        %value = view.load %a_view[%source_m, %source_k] : view<[%m_size]x[%k_size]xf32> -> f32
        scf.yield %value : f32
      }} else {{
        scf.yield %zero : f32
      }}
      view.store %a_value, %lds_view[%lds_slot] : f32, view<{lds}xf32>
    }}
    scf.for %slot = [%workitem to %span_w step %threads] {{
      %slab_row = index.div %slot, %kc : index
      %slab_k = index.rem %slot, %kc : index
      %lds_row = index.mul %slab_row, %row : index
      %lds_base = index.add %lds_row, %slab_k : index
      %lds_slot = index.add %lds_base, %slab_a : index
      %source_k = index.add %k_base, %slab_k : index
      %source_n = index.add %base_n, %slab_row : index
      %w_value = view.load %w_view[%source_n, %source_k] : view<[%n_size]x[%k_size]xf32> -> f32
      view.store %w_value, %lds_view[%lds_slot] : f32, view<{lds}xf32>
    }}
    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)
""")

    for i in range(micro_m):
        w(f"    %a_row{i} = index.add %local_m0, %c{i} : index")
        w(f"    %a_base{i} = index.mul %a_row{i}, %row : index")
    for j in range(micro_n):
        w(f"    %w_col{j} = index.add %local_n0, %c{j} : index")
        w(f"    %w_off{j} = index.mul %w_col{j}, %row : index")
        w(f"    %w_base{j} = index.add %w_off{j}, %slab_a : index")

    runs = [n.replace("%next", "%run") for n in nexts]
    init_inner = ", ".join(f"{r} = {s} : f32" for r, s in zip(runs, sums))
    w(f"    {', '.join(nexts)} = scf.for %kk = [%c0 to %kc step %c1]({init_inner}) -> ({types}) {{")
    for i in range(micro_m):
        w(f"      %a_slot{i} = index.add %a_base{i}, %kk : index")
        w(f"      %a_value{i} = view.load %lds_view[%a_slot{i}] : view<{lds}xf32> -> f32")
    for j in range(micro_n):
        w(f"      %w_slot{j} = index.add %w_base{j}, %kk : index")
        w(f"      %w_value{j} = view.load %lds_view[%w_slot{j}] : view<{lds}xf32> -> f32")
    for i in range(micro_m):
        for j in range(micro_n):
            w(f"      %out{i}_{j} = scalar.fmaf<contract> %a_value{i}, %w_value{j}, %run{i}_{j} : f32")
    outs = [f"%out{i}_{j}" for i in range(micro_m) for j in range(micro_n)]
    w(f"      scf.yield {', '.join(outs)} : {types}")
    w("    }")
    w("    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    w(f"    scf.yield {', '.join(nexts)} : {types}")
    w("  }\n")

    for j in range(micro_n):
        w(f"  %out_n_local{j} = index.add %local_n0, %c{j} : index")
        w(f"  %out_n{j} = index.add %base_n, %out_n_local{j} : index")
        w(f"  %bias{j} = view.load %bias_view[%out_n{j}] : view<[%n_size]xf32> -> f32")
    for i in range(micro_m):
        w(f"  %out_m_local{i} = index.add %local_m0, %c{i} : index")
        w(f"  %out_m{i} = index.add %base_m, %out_m_local{i} : index")
        w(f"  %in_range{i} = index.cmp ult, %out_m{i}, %m_size : index")
        w(f"  scf.if %in_range{i} {{")
        for j in range(micro_n):
            w(f"    %result{i}_{j} = scalar.addf %acc{i}_{j}, %bias{j} : f32")
            w(f"    view.store %result{i}_{j}, %c_view[%out_m{i}, %out_n{j}] : f32, view<[%m_size]x[%n_size]xf32>")
        w("  }")
    w("  kernel.return\n}")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    kernels = Path(__file__).resolve().parent.parent / "kernels"
    # 32x32 was measured too and lost everywhere: four times the workgroups,
    # but 2x2 micro-tiles halve the compute-to-LDS ratio. 64x32 keeps the good
    # ratio in M while doubling the workgroup count, which is what the narrow
    # N=384 projections need on a 40-CU part. See docs/notes.md.
    for tile_m, tile_n, suffix in ((64, 64, ""), (64, 32, "_narrow")):
        text = generate(tile_m, tile_n, suffix)
        path = kernels / f"matmul_bias_f32{suffix}.loom"
        path.write_text(text)
        print(f"wrote {path.relative_to(kernels.parent)} ({tile_m}x{tile_n})")
